package com.eking.spmanager.controller;

/**
 * @Author Yulin.Wang
 * @Date 2019-01-18
 * @Description
 **/

import com.eking.spmanager.entity.User;
import com.eking.spmanager.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.eking.spmanager.*;

import javax.servlet.http.HttpServletRequest;
import java.util.List;

@Controller         // Controller ,could ignore the notation - ResponseBody
@RequestMapping("/")
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserService userService;

    @PostMapping("add")
    @ResponseBody
    public String addUser(User user) {
        userService.addSingleUser(user);
        return "user info Saved!";
    }

    @GetMapping("login")
    String test(HttpServletRequest request) {
        request.setAttribute("key", "----index----");
        return "index";
    }

    @RequestMapping(value = "all")
    @ResponseBody
    public List<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userService.findAllUser();
    }
}
